/**
 * RFC 8785 JCS canonicalization parametric test — TS side.
 *
 * Mirror of `paladin-server/tests/test_canonical.py:TestCrossLanguageFixtures`.
 * Both languages MUST produce byte-identical canonical output for every
 * fixture in the shared `tests/fixtures/jcs-fixtures.json` file.
 *
 * If this drifts vs the Python harness:
 *   - The signed-payload byte-equality claim (load-bearing for v0.2.0
 *     Layer 3 verification) is broken.
 *   - Plugin-computed `requestHash` would not match server-computed
 *     `requestHash`, breaking request-binding (closes R8 Sec CRITICAL-1
 *     replay attack).
 *   - The two languages disagree on RFC 8785 — fix the implementation
 *     that diverges from spec, not the fixture.
 *
 * Generation: tests/fixtures/jcs-fixtures.json is generated by
 * `scripts/generate-jcs-fixtures.mjs` using @truestamp/canonify as ground
 * truth. Re-run that script after any TOKEN_REGISTRY / signed-payload
 * shape change.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { canonicalize } from "../src/utils/paladin-canonical";

const FIXTURES_PATH = resolve(__dirname, "fixtures", "jcs-fixtures.json");

interface Fixture {
  name: string;
  input: unknown;
  expected_canonical: string;
}

// Read once at module load — fixtures shouldn't change during a test run.
const fixtures = JSON.parse(readFileSync(FIXTURES_PATH, "utf-8")) as Fixture[];

describe("Cross-language JCS fixtures (50 entries; byte-equal with Python pyjcs)", () => {
  it("loads exactly 50 fixtures", () => {
    expect(fixtures).toHaveLength(50);
  });

  it("all fixture names are unique", () => {
    const names = fixtures.map((f) => f.name);
    expect(new Set(names).size).toBe(names.length);
  });

  // Parametric: one test per fixture so a failure pinpoints the exact name.
  for (const fix of fixtures) {
    it(fix.name, () => {
      const actual = canonicalize(fix.input);
      expect(actual).toBe(fix.expected_canonical);
    });
  }
});

describe("Cross-language drift summary (single aggregating test)", () => {
  // Aggregating test mirrors the Python harness shape — useful for CI
  // where seeing all failures at once helps diagnose systematic bugs
  // (e.g., a unicode-escape divergence affects many fixtures).
  it("every fixture's canonicalize() output matches expected_canonical", () => {
    const failures: string[] = [];
    for (const fix of fixtures) {
      const actual = canonicalize(fix.input);
      if (actual !== fix.expected_canonical) {
        failures.push(
          `${fix.name}:\n  expected: ${JSON.stringify(fix.expected_canonical)}\n  actual:   ${JSON.stringify(actual)}`,
        );
      }
    }
    if (failures.length > 0) {
      throw new Error(`Cross-language drift:\n${failures.join("\n")}`);
    }
  });
});
